package FrmExpendedora;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOHDLS
 */
public class FrmInicio extends javax.swing.JFrame {
    int producto, boton, dinero;
    int count1 = 0;
    int count2 = 0;
    int count3 = 0;
    int count4 = 0;
    int count5 = 0;
    int count6 = 0;
    int count7 = 0;
    int count8 = 0;
    
    int click_actuales = 1;
    int click_maximo = 7;
    
    /**
     * Creates new form inicio
     */
    public FrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCocaNormal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCocaLight = new javax.swing.JButton();
        btnCocaSinAzucar = new javax.swing.JButton();
        btnCocaZero = new javax.swing.JButton();
        btnCocaCafe = new javax.swing.JButton();
        btnCocaCherry = new javax.swing.JButton();
        btnCocaEnergy = new javax.swing.JButton();
        btnCocaVainilla = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtpantalla = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDinero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Efectivo");

        btnCocaNormal.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca lata.png"))); // NOI18N
        btnCocaNormal.setText("Normal $17");
        btnCocaNormal.setToolTipText("");
        btnCocaNormal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaNormal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaNormalActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca cola banner.png"))); // NOI18N

        btnCocaLight.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca light.png"))); // NOI18N
        btnCocaLight.setText("Light $17");
        btnCocaLight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaLight.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaLightActionPerformed(evt);
            }
        });

        btnCocaSinAzucar.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaSinAzucar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca sin azucar.png"))); // NOI18N
        btnCocaSinAzucar.setText("Sin Azúcar $17");
        btnCocaSinAzucar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaSinAzucar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaSinAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaSinAzucarActionPerformed(evt);
            }
        });

        btnCocaZero.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca zero.png"))); // NOI18N
        btnCocaZero.setText("Zero $17");
        btnCocaZero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaZero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaZeroActionPerformed(evt);
            }
        });

        btnCocaCafe.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca cafe.png"))); // NOI18N
        btnCocaCafe.setText("Café $17");
        btnCocaCafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaCafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaCafeActionPerformed(evt);
            }
        });

        btnCocaCherry.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaCherry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca cherry.png"))); // NOI18N
        btnCocaCherry.setText("Cherry $17");
        btnCocaCherry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaCherry.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaCherry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaCherryActionPerformed(evt);
            }
        });

        btnCocaEnergy.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaEnergy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca energy.png"))); // NOI18N
        btnCocaEnergy.setText("Energy $17");
        btnCocaEnergy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaEnergy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaEnergyActionPerformed(evt);
            }
        });

        btnCocaVainilla.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaVainilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca vainilla.png"))); // NOI18N
        btnCocaVainilla.setText("Naranja $17");
        btnCocaVainilla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaVainilla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaVainilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaVainillaActionPerformed(evt);
            }
        });

        btnCobrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setToolTipText("");
        lblResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setText("$500");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("$200");

        jButton4.setText("$100");

        jButton5.setText("$50");

        jButton6.setText("$20");

        jButton7.setText("$10");

        jButton8.setText("$5");

        jButton9.setText("$2");

        jButton10.setText("$1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("A Pagar:");

        txtpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantallaActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Efectivo");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Introducido:");

        txtDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDineroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(txtpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                            .addComponent(lblResultado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCocaNormal, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(btnCocaCafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addComponent(btnCocaCherry, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCocaEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCocaVainilla, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addComponent(btnCocaLight, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCocaSinAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCocaZero, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(7, 7, 7)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCocaNormal)
                    .addComponent(btnCocaLight)
                    .addComponent(btnCocaSinAzucar)
                    .addComponent(btnCocaZero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCocaCafe)
                    .addComponent(btnCocaCherry)
                    .addComponent(btnCocaEnergy)
                    .addComponent(btnCocaVainilla))
                .addGap(27, 27, 27)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultado))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        dinero=Integer.parseInt(txtpantalla.getText());
        float total, preciococa=17, cambio;
        if(boton==1){
            total=producto*preciococa;
            cambio=dinero-total;
            if(cambio>0){
                lblResultado.setText(String.valueOf("tome su producto y su cambio "+cambio));
            }else{
                lblResultado.setText(String.valueOf("tome su producto y su cambio")); 
            }if(cambio<0){
                lblResultado.setText(String.valueOf("Dinero Insufiente vuelva a intentarlo"));
            }
        }
        total=0;
        cambio=0;
        dinero=0;
        producto=0;
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnCocaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaNormalActionPerformed
    producto=producto+1;
    boton=1;
    
    if(click_actuales == click_maximo){
     JOptionPane.showMessageDialog(null, "La valvula esta por debajo del 25%, la valvula se cerrara");

    }else{
    click_actuales++;
    }
    }//GEN-LAST:event_btnCocaNormalActionPerformed

    private void btnCocaLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaLightActionPerformed
    producto=producto+1;
    boton=1;
    
    count2++;
    String numero = String.valueOf(count2);
    btnCocaLight.setText(numero);
    }//GEN-LAST:event_btnCocaLightActionPerformed

    private void btnCocaSinAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaSinAzucarActionPerformed
    producto=producto+1;
    boton=1;
    
    count3++;
    String numero = String.valueOf(count3);
    btnCocaSinAzucar.setText(numero);
    }//GEN-LAST:event_btnCocaSinAzucarActionPerformed

    private void btnCocaZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaZeroActionPerformed
    producto=producto+1;
    boton=1;
    
    count4++;
    String numero = String.valueOf(count4);
    btnCocaZero.setText(numero);
    }//GEN-LAST:event_btnCocaZeroActionPerformed

    private void btnCocaCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaCafeActionPerformed
    producto=producto+1;
    boton=1;
    
    count5++;
    String numero = String.valueOf(count5);
    btnCocaCafe.setText(numero);
    }//GEN-LAST:event_btnCocaCafeActionPerformed

    private void btnCocaCherryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaCherryActionPerformed
    producto=producto+1;
    boton=1;
    
    count6++;
    String numero = String.valueOf(count6);
    btnCocaCherry.setText(numero);
    }//GEN-LAST:event_btnCocaCherryActionPerformed

    private void btnCocaEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaEnergyActionPerformed
    producto=producto+1;
    boton=1;
    
    count7++;
    String numero = String.valueOf(count7);
    btnCocaEnergy.setText(numero);
    }//GEN-LAST:event_btnCocaEnergyActionPerformed

    private void btnCocaVainillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaVainillaActionPerformed
    producto=producto+1;
    boton=1;
    
    count8++;
    String numero = String.valueOf(count8);
    btnCocaVainilla.setText(numero);
    }//GEN-LAST:event_btnCocaVainillaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpantallaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDineroActionPerformed
        
    }//GEN-LAST:event_txtDineroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnCocaCafe;
    private javax.swing.JButton btnCocaCherry;
    private javax.swing.JButton btnCocaEnergy;
    private javax.swing.JButton btnCocaLight;
    private javax.swing.JButton btnCocaNormal;
    private javax.swing.JButton btnCocaSinAzucar;
    private javax.swing.JButton btnCocaVainilla;
    private javax.swing.JButton btnCocaZero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtDinero;
    private javax.swing.JTextField txtpantalla;
    // End of variables declaration//GEN-END:variables
}
